// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance.Context;

#nullable disable

namespace Persistance.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250721084919_Add database again")]
    partial class Adddatabaseagain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Domain.Models.Todo", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isRemoved")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Todo");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            IsCompleted = false,
                            Title = "Read the book Clean Architecture",
                            date = new DateOnly(2025, 7, 11),
                            isRemoved = false
                        },
                        new
                        {
                            ID = 2L,
                            IsCompleted = false,
                            Title = "Do ASP.NET project exercises",
                            date = new DateOnly(2025, 7, 10),
                            isRemoved = false
                        },
                        new
                        {
                            ID = 3L,
                            IsCompleted = false,
                            Title = "Buy a new book",
                            date = new DateOnly(2025, 7, 10),
                            isRemoved = false
                        },
                        new
                        {
                            ID = 4L,
                            IsCompleted = true,
                            Title = "Write an article about the Repository Pattern",
                            date = new DateOnly(2025, 7, 10),
                            isRemoved = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
