// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance.Context;

#nullable disable

namespace Persistance.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Domain.Models.Todo", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("date")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Todo");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            IsCompleted = false,
                            Title = "خواندن کتاب Clean Architecture",
                            date = new DateOnly(2025, 7, 11)
                        },
                        new
                        {
                            ID = 2L,
                            IsCompleted = false,
                            Title = "انجام تمرینات پروژه ASP.NET",
                            date = new DateOnly(2025, 7, 10)
                        },
                        new
                        {
                            ID = 3L,
                            IsCompleted = false,
                            Title = "خرید کتاب جدید",
                            date = new DateOnly(2025, 7, 10)
                        },
                        new
                        {
                            ID = 4L,
                            IsCompleted = true,
                            Title = "نوشتن مقاله درباره‌ی Repository Pattern",
                            date = new DateOnly(2025, 7, 10)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
